project:
  type: website

website:
  margin-header: |
    ![](/fig/slab.png)
  navbar:
    logo: "sfasu.png"
    right:
      - href: index.qmd
        text: Home
      - linear.qmd
      - ml.qmd
      - gm.qmd

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true

editor: source

