project:
  type: website

website:
  title: "perdiz.3"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - linear.qmd
      - ml.qmd
      - gm.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: source

